export const MUTATE_MODEL = 'MUTATE_MODEL';
export const MUTATE_SHELL_OUTPUT = 'MUTATE_SHELL_OUTPUT';
export const MUTATE_SHELL_ERRORS = 'MUTATE_SHELL_ERRORS';
export const MUTATE_DATABASE = 'MUTATE_DATABASE';
export const MUTATE_SHARE = 'MUTATE_SHARE';
